### ISSUE TITLE
The same activity for view and edit a note

### ISSUE THREAD

**Issue by avently** [BijoySingh/Material-Notes-Android-App#10]
Now you use one activity for previewing a note and another activity for editing a note. It's not so cool as to use one activity for that purpose. Also an "edit" button is useless.  If users taps on a note's view edit action should be called automatically.

**Comment by BijoySingh** [comment]
Sure, it will be "cool" to do it but I wont consider it an issue. 
It barely adds any value to the user, with an additional overhead of making the activity difficult to write.

Also, I dont agree clicking on the note should open it in edit mode. Because this is a rich editor, the experience of viewing the note can be different from writing it. Especially after recent markdown additions.
