### ISSUE TITLE
Absent Options

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [BijoySingh/Material-Notes-Android-App#29]
The options for adding a Heading, sub heading, check box, etc. do not appear on the bottom of a new note while creating. Only after saving that note and then opening it again do those options appear at the bottom.

Version 3.5.0. F-Droid

**Comment by BijoySingh** [comment]
Yes, the default creation was the "Simple Note Creation" which would happen when you press "add a quick note". Click the (Tt) button would open the advance flow with a blank note.

However:
This has changed. I will create release for FDroid once the latest is test and released on play store. 

This issue is resolved, but I'll keep it open till I create the FDroid release :)

**Comment by iknownothingaboutcomputers** [comment]
@BijoySingh Thanks, Bijoy. You rock!
